// Maps ESPN/external API team names → our internal names
// ESPN often uses anglicized or alternate spellings
const ESPN_TO_INTERNAL = {
  // Straightforward
  'Mexico':           'Mexico',
  'South Africa':     'South Africa',
  'South Korea':      'South Korea',
  'Czech Republic':   'Czechia',
  'Czechia':          'Czechia',
  'Canada':           'Canada',
  'Bosnia & Herzegovina': 'Bosnia-Herzegovina',
  'Bosnia-Herzegovina':   'Bosnia-Herzegovina',
  'Qatar':            'Qatar',
  'Switzerland':      'Switzerland',
  'Brazil':           'Brazil',
  'Morocco':          'Morocco',
  'Haiti':            'Haiti',
  'Scotland':         'Scotland',
  'USA':              'USA',
  'United States':    'USA',
  'Paraguay':         'Paraguay',
  'Australia':        'Australia',
  'Turkey':           'Türkiye',
  'Türkiye':          'Türkiye',
  'Germany':          'Germany',
  'Curacao':          'Curacao',
  'Curaçao':          'Curacao',
  "Ivory Coast":      "Côte d'Ivoire",
  "Cote d'Ivoire":    "Côte d'Ivoire",
  "Côte d'Ivoire":    "Côte d'Ivoire",
  'Ecuador':          'Ecuador',
  'Netherlands':      'Netherlands',
  'Japan':            'Japan',
  'Sweden':           'Sweden',
  'Tunisia':          'Tunisia',
  'Belgium':          'Belgium',
  'Egypt':            'Egypt',
  'Iran':             'IR Iran',
  'IR Iran':          'IR Iran',
  'New Zealand':      'New Zealand',
  'Spain':            'Spain',
  'Cape Verde':       'Cabo Verde',
  'Cabo Verde':       'Cabo Verde',
  'Saudi Arabia':     'Saudi Arabia',
  'Uruguay':          'Uruguay',
  'France':           'France',
  'Senegal':          'Senegal',
  'Iraq':             'Iraq',
  'Norway':           'Norway',
  'Argentina':        'Argentina',
  'Algeria':          'Algeria',
  'Austria':          'Austria',
  'Jordan':           'Jordan',
  'Portugal':         'Portugal',
  'Congo DR':         'Congo DR',
  'DR Congo':         'Congo DR',
  'Democratic Republic of Congo': 'Congo DR',
  'Uzbekistan':       'Uzbekistan',
  'Colombia':         'Colombia',
  'England':          'England',
  'Croatia':          'Croatia',
  'Ghana':            'Ghana',
  'Panama':           'Panama',
};

function normalizeTeamName(name) {
  if (!name) return name;
  return ESPN_TO_INTERNAL[name] || name;
}

module.exports = { normalizeTeamName, ESPN_TO_INTERNAL };
